PRAGMA foreign_keys = ON;
-- Runtime initialization must additionally configure local-disk WAL, busy_timeout and synchronous=FULL.
CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, name TEXT NOT NULL, checksum TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE solutions(id TEXT PRIMARY KEY, workspace_instance_id TEXT NOT NULL UNIQUE, profile TEXT NOT NULL, config_hash TEXT NOT NULL, event_seq INTEGER NOT NULL DEFAULT 0 CHECK(event_seq>=0), full_scan_required INTEGER NOT NULL DEFAULT 1 CHECK(full_scan_required IN(0,1)));
CREATE TABLE projects(id TEXT PRIMARY KEY, solution_id TEXT NOT NULL REFERENCES solutions(id), repo_id TEXT NOT NULL, relative_path TEXT NOT NULL, UNIQUE(solution_id,repo_id,relative_path));
CREATE TABLE files(id INTEGER PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), path TEXT NOT NULL, observed_hash TEXT, indexed_hash TEXT, desired_generation INTEGER NOT NULL DEFAULT 0, indexed_generation INTEGER NOT NULL DEFAULT 0, deleted INTEGER NOT NULL DEFAULT 0 CHECK(deleted IN(0,1)), export_fingerprint TEXT, CHECK(desired_generation>=indexed_generation AND indexed_generation>=0), UNIQUE(project_id,path));
CREATE TABLE dirty_files(file_id INTEGER PRIMARY KEY REFERENCES files(id) ON DELETE CASCADE, target_generation INTEGER NOT NULL CHECK(target_generation>=0), first_seen TEXT NOT NULL, last_seen TEXT NOT NULL, reason TEXT NOT NULL);
CREATE TABLE nodes(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), owner_file_id INTEGER REFERENCES files(id) ON DELETE CASCADE, kind TEXT NOT NULL, qualified_name TEXT NOT NULL, record_json TEXT NOT NULL);
CREATE INDEX nodes_project_name ON nodes(project_id,qualified_name);
CREATE TABLE edges(id TEXT PRIMARY KEY, owner_file_id INTEGER REFERENCES files(id) ON DELETE CASCADE, source_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE, target_id TEXT, unresolved_target TEXT, target_project_id TEXT NOT NULL, kind TEXT NOT NULL, resolution TEXT NOT NULL CHECK(resolution IN('exact_static','inferred_static','annotated','unresolved')), record_json TEXT NOT NULL, CHECK((target_id IS NOT NULL AND unresolved_target IS NULL) OR (target_id IS NULL AND unresolved_target IS NOT NULL)));
-- Cross-project targets may be in another snapshot, so target_id is validated at reconciliation/catalog publication, not as a local foreign key.
CREATE INDEX edges_source ON edges(source_id,kind);
CREATE INDEX edges_target ON edges(target_project_id,target_id,kind);
CREATE TABLE jobs(id TEXT PRIMARY KEY, solution_id TEXT NOT NULL REFERENCES solutions(id), kind TEXT NOT NULL, scope_key TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN('PENDING','LEASED','RUNNING','RETRY_WAIT','SUCCEEDED','FAILED','CANCEL_REQUESTED','CANCELLED','SUPERSEDED')), priority INTEGER NOT NULL DEFAULT 0, target_event_seq INTEGER NOT NULL, attempt INTEGER NOT NULL DEFAULT 0, fence INTEGER NOT NULL DEFAULT 0, lease_owner TEXT, lease_until TEXT, ready_at TEXT NOT NULL, created_at TEXT NOT NULL, last_error_code TEXT);
CREATE UNIQUE INDEX jobs_pending_dedup ON jobs(solution_id,kind,scope_key) WHERE state IN('PENDING','RETRY_WAIT');
CREATE INDEX jobs_ready ON jobs(state,ready_at,priority);
CREATE TABLE job_files(job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE, target_generation INTEGER NOT NULL, input_hash TEXT, PRIMARY KEY(job_id,file_id));
CREATE TABLE job_attempts(job_id TEXT NOT NULL REFERENCES jobs(id), attempt INTEGER NOT NULL, fence INTEGER NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, exit_code TEXT, evidence_ref TEXT, PRIMARY KEY(job_id,attempt));
CREATE TABLE graph_revisions(id INTEGER PRIMARY KEY, solution_id TEXT NOT NULL REFERENCES solutions(id), event_seq INTEGER NOT NULL, profile TEXT NOT NULL, source_fingerprint TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE publish_outbox(id TEXT PRIMARY KEY, revision_id INTEGER NOT NULL REFERENCES graph_revisions(id), project_id TEXT REFERENCES projects(id), operation TEXT NOT NULL CHECK(operation IN('project','catalog')), state TEXT NOT NULL CHECK(state IN('PENDING','STAGED','PUBLISHED','FAILED')), idempotency_key TEXT NOT NULL UNIQUE, generation_id TEXT, last_error TEXT);
CREATE TABLE published_generations(project_id TEXT NOT NULL REFERENCES projects(id), generation_id TEXT NOT NULL, revision_id INTEGER NOT NULL REFERENCES graph_revisions(id), lane TEXT NOT NULL CHECK(lane IN('live','checkpoint')), manifest_hash TEXT NOT NULL, published_at TEXT NOT NULL, PRIMARY KEY(project_id,generation_id,lane));
CREATE TABLE catalog_refs(catalog_generation_id TEXT NOT NULL, project_id TEXT NOT NULL REFERENCES projects(id), generation_id TEXT NOT NULL, lane TEXT NOT NULL CHECK(lane IN('live','checkpoint')), PRIMARY KEY(catalog_generation_id,project_id,lane));
CREATE INDEX catalog_generation_roots ON catalog_refs(project_id,generation_id,lane);
CREATE TABLE runtime_checkpoints(id TEXT PRIMARY KEY, solution_id TEXT NOT NULL REFERENCES solutions(id), source_mode TEXT NOT NULL CHECK(source_mode IN('worktree','staged','commit')), source_revision TEXT, catalog_generation_id TEXT NOT NULL, verified_at TEXT NOT NULL);
CREATE TABLE audit_events(id INTEGER PRIMARY KEY, event_type TEXT NOT NULL, solution_id TEXT, actor TEXT NOT NULL, redacted_json TEXT NOT NULL, created_at TEXT NOT NULL);
PRAGMA user_version = 1;
